spring:
    application:
        name: bisaya-gateway
    cloud:
        config:
            uri: http://127.0.0.1:9000/config

zuul:
    routes:
        bisaya-order:
            path: /order/**
            retryable: true
            sensitive-headers:
            strip-prefix: false
        bisaya-production:
            path: /production/**
            retryable: true
            sensitive-headers:
            strip-prefix: false
    add-proxy-headers: true

ribbon:
    ConnectTimeout: 6000
    ReadTimeout: 120000
    
server:
    port: 9002
    context-path: /
    address: 0.0.0.0
    
eureka:
    instance:
        protocol: http
        ip-address: 127.0.0.1
        port: 9001
        context-path: /registry
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: ${eureka.instance.protocol}://${eureka.instance.ip-address}:${eureka.instance.port}${eureka.instance.context-path}/eureka/
  