spring:
    application:
        name: bisaya-production
    cloud:
        config:
            uri: http://127.0.0.1:9000/config
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            use-new-id-generator-mappings: true
    datasource:
        hikari:
            maximum-pool-size: 20
            pool-name: datasource-development
            connection-test-query: SELECT 1
        type: com.zaxxer.hikari.HikariDataSource
        username: montrichard-admin
        password: 1234
        url: jdbc:postgresql://127.0.0.1:5432/bisaya-production
        driver-class-name: org.postgresql.Driver
server:
    port: 9003
    context-path: /production
    address: 0.0.0.0

    
eureka:
    instance:
        protocol: http
        ip-address: 127.0.0.1
        port: 9001
        context-path: /registry
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: ${eureka.instance.protocol}://${eureka.instance.ip-address}:${eureka.instance.port}${eureka.instance.context-path}/eureka/